output					.equ vRAM+0000
stack					.equ vRAM+1000
stackPtr				.equ vRAM+2000
outputPtr				.equ vRAM+2003
dataLength				.equ vRAM+2006
programPtr				.equ vRAM+2009
programData				.equ UserMem
AmountOfEnds			.equ vRAM+2012
varname_offset			.equ vRAM+2013
programNameLength		.equ vRAM+2016
InputStartData			.equ vRAM+2017
labelPtr				.equ vRAM+2020
labelStack				.equ vRAM+2023
gotoPtr					.equ vRAM+3020
gotoStack				.equ vRAM+3023
programDataOffsetPtr	.equ vRAM+4020
programDataOffsetStack	.equ vRAM+4023
programDataDataPtr		.equ vRAM+5020
programDataData			.equ vRAM+5023
myFlags					.equ 021h
prev_is_number			.equ 0
chain_operators			.equ 1
has_already_input		.equ 2
fixed_output			.equ 3
typeNumber				.equ 1
typeOperator			.equ 2
typeFunction			.equ 3
typeVariable			.equ 4
typeChain				.equ 5
typeIf					.equ 6
typeWhile				.equ 7
typeRepeat				.equ 8
ChainLast				.equ 0
ChainFirst				.equ 1
ChainPush				.equ 2