	.db "Begin", 0
	.db "End", 0
	.db "SetColor", 0
	.db "SetDefaultPalette", 0
	.db "SetPalette", 0
	.db "FillScreen", 0
	.db "SetPixel", 0
	.db "GetPixel", 0
	.db "GetDraw", 0
	.db "SetDraw", 0
	.db "SwapDraw", 0
	.db "Blit", 0
	.db "BlitLines", 0
	.db "BlitArea", 0
	.db "PrintChar", 0
	.db "PrintInt", 0
	.db "PrintUInt", 0
	.db "PrintString", 0
	.db "PrintStringXY", 0
	.db "SetTextXY", 0
	.db "SetTextBGColor", 0
	.db "SetTextFGColor", 0
	.db "SetTextTransparentColor", 0
	.db "SetCustomFontData", 0
	.db "SetCustomFontSpacing", 0
	.db "SetMonospaceFont", 0
	.db "GetStringWidth", 0
	.db "GetCharWidth", 0
	.db "GetTextX", 0
	.db "GetTextY", 0
	.db "Line", 0
	.db "HorizLine", 0
	.db "VertLine", 0
	.db "Circle", 0
	.db "FillCircle", 0
	.db "Rectangle", 0
	.db "FillRectangle", 0
	.db "Line_NoClip", 0
	.db "HorizLine_NoClip", 0
	.db "VertLine_NoClip", 0
	.db "FillCircle_NoClip", 0
	.db "Rectangle_NoClip", 0
	.db "FillRectangle_NoClip", 0
	.db "SetClipRegion", 0
	.db "GetClipRegion", 0
	.db "ShiftDown", 0
	.db "ShiftUp", 0
	.db "ShiftLeft", 0
	.db "ShiftRight", 0
	.db "Tilemap", 0
	.db "Tilemap_NoClip", 0
	.db "TransparentTilemap", 0
	.db "TransparentTilemap_NoClip", 0
	.db "TilePtr", 0
	.db "TilePtrMapped", 0
	.db "LZDecompress", 0
	.db "AllocSprite", 0
	.db "Sprite", 0
	.db "TransparentSprite", 0
	.db "Sprite_NoClip", 0
	.db "TransparentSprite_NoClip", 0
	.db "GetSprite_NoClip", 0
	.db "ScaledSprite_NoClip", 0
	.db "ScaledTransparentSprite_NoClip", 0
	.db "FlipSpriteY", 0
	.db "FlipSpriteX", 0
	.db "RotateSpriteC", 0
	.db "RotateSpriteCC", 0
	.db "RotateSpriteHalf", 0
	.db "Polygon", 0
	.db "Polygon_NoClip", 0
	.db "FillTriangle", 0
	.db "FillTriangle_NoClip", 0
	.db "LZDecompressSprite", 0
	.db "SetTextScale", 0